baseURL = "https://national-beverage-company.netlify.app/"
languageCode = "en-us"
[[menu.main]]
name = "IDX Property Organizer"
parent = "Insurance Plans"
url = "https://search.idxhome.com//organizer/login/133407"
weight = 3
[[menu.main]]
name = "Search the MLS"
parent = "Buyers"
url = "https://search.idxhome.com/homesearch/133407"
weight = 2
[[menu.main]]
name = "Services"
weight = 2
[[menu.main]]
name = "About"
weight = 3
[[menu.main]]
name = "Contact"
weight = 6
[[menu.main]]
name = "Home"
url = "/"
weight = 1