baseURL = "https://www.allthesmokeofficial.com/"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = "true"
languageCode = "en-us"
[[menu.main]]
name = "Apparel"
parent = "Products"
url = "/apparels"
weight = 2
[[menu.main]]
name = "Strains"
parent = "Products"
url = "/shop/"
weight = 1
[[menu.main]]
name = "Products"
weight = 3
[[menu.main]]
name = "Verification"
url = "/verification"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
