baseURL = "https://allthesmoke.netlify.app/"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = "true"
languageCode = "en-us"
[[menu.main]]
name = "Resources"
weight = 4
[[menu.main]]
name = "Home"
url = "/"
weight = 1
